### ISSUE TITLE
Upload to Hackage?

### ISSUE THREAD

**Issue by MonrealRyan** [bitemyapp/sendgrid-haskell#1]
Hi,

Want to try this on my current project. 
Q: Is the project already on the hackage?
Q: Also do you have some snippet for implementation?

**Comment by bitemyapp** [comment]
@MonrealRyan oh my, this is very incomplete!

It's not currently on Hackage and I don't think I have any working snippets (it's not done, as I mentioned), but if you're willing to take the client forward I'll help you with getting it ready for Hackage and upload it. I can't commit too much time here as [the book](http://haskellbook.com/) is my primary focus for the time being.

To get an idea of how I like to do things, take a look at [Bloodhound](https://github.com/bitemyapp/bloodhound) for ideas.

**Comment by MonrealRyan** [comment]
@bitemyapp - thanks for the reply, maybe i should wait for this to finish before i use it. :thumbsup:

**Comment by bitemyapp** [comment]
@MonrealRyan the contract I was writing this for ended abruptly and isn't like to resume, so unless somebody pays me to work on this, I'm not going to finish it - sorry. You're welcome to reuse anything you find here (see the `LICENSE`) if it's useful to you.

**Comment by bitemyapp** [comment]
Closing for now, offer still stands to help you if you're willing to take responsibility for getting it where it needs to go.
